#' @title
#' Simulate a Multi-Arm-Bandit Trial from an Existing Randomized Controlled Trial, With Bernoulli Distributed Outcomes.
#' @name mab_from_rct.bernoulli
#' @description Simulates a response-adaptive, Multi-Arm-Bandit (MAB) trial using experimental data
#' from an original randomized controlled trial (RCT), and adaptive inference strategies
#' described in \href{https://www.pnas.org/doi/pdf/10.1073/pnas.2014602118}{Hadad et al. (2021)}
#' and \href{https://onlinelibrary.wiley.com/doi/abs/10.1111/ajps.12597}{Offer-Westort et al. (2021)} to robustly estimate
#' treatment effects. See the details and vignettes to learn more.
#'
#' @param formula A `formula` object specifying outcome variable, treatment indicator, treatment blocking and treatment clustering. The treatment variable should always be the first variable following `~`
#' (Additional covariates to be added in later updates). Clustering and blocking variables
#' should being included in specific `block()` or `cluster()` groups in the formula, e.g. `outcome ~ treatment + block(x1, x2, x3) + cluster(x4)`. Given a set of probabilities for assigning treatments,
#' treatment blocking applies these within each block indpendently instead of the whole sample, while for clustering assignment occurs at the cluster level instead of the individual level, so all observations
#' in a cluster have the same treatment. When blocks and clusters are specified together each cluster must be fully nested in a single block. See below for details. To speciy without clustering or blocking
#' simply do not provide them in the formula. Clusters can only ever be given by 1 variable, while blocks can be a combination of variables.
#'
#' @param data A `data.frame`, `data.table`, or any object which inherits from `data.frame`, containing input data from the trial. This should be the results
#' of a traditional Randomized Controlled Trial (RCT).
#'
#' @param algorithm A character string specifying the MAB algorithm to use. Options are `"Thompson"` or `"UCB1"`, ignoring case. Algorithm
#' defines the adaptive assignment process. For more details on these specific algorithms see
#' \href{https://www.jstor.org/stable/2332286}{Thompson 1933};\href{https://doi.org/10.1023/A:1013689704352Auer et al. 2002};
#' \href{https://proceedings.mlr.press/v23/agrawal12.html}{Agrawal and Goyal 2012};\href{https://arxiv.org/abs/1402.6028}{Kuleshov and Precup 2014} and
#' \href{https://arxiv.org/abs/1904.07272}{Slivkins 2024}.
#'
#' @param control_augment Minimum proportion of each treatment assignment wave guarenteed to recieve the treatment labelled as "Control". Ranges from 0 to 1,
#' and the default is 0. It is not recommended to use this in conjunction with `random_assign_prop`.
#'
#' @param control_condition Value of the control condition. Only necessary when `control_augment` is greater than 0. Internally this value
#' is coerced to a string, so it should be passed as a string, or a type that can easily be converted to a string.
#
#' @param random_assign_prop Proportion of each treatment assignment wave assigned via static, equal probabilities of assignment instead of
#' the adaptively updated probabilities generated by the MAB algorithm. Ranges from 0 to 1, default is 0. It is not recommended to use
#' this in conjunction with `control_augment`. When batch sizes are small and `random_assign_prop * batch_size < 1`, this value instead represents
#' a probability instead of a raw proportion. Under clustering, its possible that `random_assign_prop` may not reflect the true proportion of units
#' selected due to the constraint that all units within a cluster have to be assigned the same treatment.
#'
#' @param period_method A character string; one of `"date"`, `"batch"`, or `"individual"`, to define the assignment into treatment waves. When using
#' `"batch"` or `"individual"`, ensure your dataset is pre-arranged in the proper order observations should be considered so that
#' groups are assigned correctly. For "date", observations will be considered in chronological order.
#' `"individual"` assignment can be computationally intensive for larger datasets.
#'
#' @param time_unit A character string specifying the unit of time for assigning periods when `period_method ="date"`.
#' Acceptable values are `"day", "week",` or `"month"`. `"month"` does not require an additional column with the months of each observation,
#' but it can accept a separate `month_col`. If `month_col` is specified, the periods follow the calendar months strictly, and when it is not
#' specified months are simply used as the time interval. For example if a dataset has dates starting on July 26th, under month based assignment and
#' a specified `month_col` the dates July 26th and August 3st would be in different periods, but if the `month_col` was not specified, they would be
#' in the same period because the dates are less than one month apart.
#'
#' @param period_length A positive integer; represents the length of each treatment period.
#' If `period_method` is "date", this length refers the number of units specified in `time_unit`.
#' (i.e., if `"day"``, 10 would be 10 days). If `period_method` = `"batch"`, this refers to the number of units in each batch.
#'
#' @param prior_periods A positive integer; number of previous periods to use
#' in the treatment assignment model. Default is `NULL`, where all prior periods are considered. See below for details.
#'
#' @param discount_rate Rate for discounting observations from earlier periods when updating assignment probabilities.
#' A value between 0 and 1, where outcomes from `k` periods ago are weighted by `discount_rate^k`. Default is 1 for no discounting.
#'
#' @param date_col Column in `data`; contains original date of event/trial. Only necessary when assigning by "Date". Must be of type `Date`, not a character string.
#' @param month_col Column in `data`; contains month of treatment. Only necessary when `time_unit = "month"`, and when periods should be determined directly by
#' the calendar months instead of month based time periods. This column can be a string/factor variable with the month names or numeric with the month number. It can easily
#' be created from your `date_col` via `lubridate::month(data[[date_col]])` or `format(data[[date_col]], "%m")`.
#'
#' @param delayed_feedback Logical; if `FALSE`, assumes instanteneous feedback for outcomes, as soon as a treatment is assigned, the outcome is realized and known.
#' If `TRUE`, delayed feedback is assumed, so as soon as treatment is assigned, a potential outcome is realized, but it is not known to the simulation, until a certain date.
#' When re-computing the adaptive assignment probabilities via Thompsom Samplings or UCB1 outcomes that have not been observed on the date the assignment are treated as failures. a
#'
#' @param success_date_col Column in `data`; contains original dates each success occurred. Only necessary when `delayed_feedback = TRUE`. Must be of type `Date`, not a character string.
#'
#' @param assignment_date_col Column in `data`; contains original dates treatments were assigned to observations. Only necessary when `delayed_feedback = TRUE`. Used to simulate imperfect
#' observation of outcomes in the simulation. Must be of type `Date`, not a character string.
#'
#' @param whole_experiment Logical; if `TRUE`, uses all past experimental data for imputing outcomes.
#' If `FALSE`, uses only data available up to the current period. In large datasets or with a high number
#' of periods, setting this to `FALSE` can be more computationally intensive, though not a significant
#' contributor to total run time. Default is `FALSE`.
#'
#' @param ndraws Number of draws used to approximate Thompson sampling probabilities. Used only when direct calculation fails or overflows. Default is
#' 5000 but can be raised or lowered depending on performance and accuracy concerns.
#'
#' @param verbose Logical; whether or not to print intermediate messages. Default is `FALSE`.
#'
#' @param r Positive integer; number of replications (under different random seed). Replications of the MAB procedure on a fixed dataset provides important diagnostic information on the stochasticity/variance of
#' the re-simulation method. Replications can be conducted in parallel, by setting an appropriate [future::plan()]. See details below.
#'
#' @param seeds An integer vector of `length(r)` containing valid seeds to define random state for each re-simulation.
#' @param keep_data Logical; Whether or not to keep the final data from each trial. Recommended `FALSE`. When` r = 1` the final data is always kept and reported.
#' @param check_args Logical; Whether or not to robustly check whether arguments are valid. Default is TRUE, and recommended
#' not to be changed.
#' @param ... Additional named arguments passed to [furrr::furrr_options()]
#'
#' @returns An object of class `mab`, containing:
#' \itemize{
#' \item `final_data`: The processed `tibble` or `data.table`, containing new columns pertaining to the results of the trial. Specifically Contains:
#' \itemize{
#' \item `period_number`: Assigned period for simulation.
#' \item `mab_*`: New treatment conditions and outcomes under the simulation.
#' \item `impute_req`: Whether observation required an imputed outcome.
#' \item `*block`: variables relating to the block specified for treatment blocking, and the concatenation
#' of that block with an observations original treatment, and new treatment.
#' \item `aipw_*` Columns containing individual Augmented Inverse Probability Weighted estimates for each observation and treatment arm.
#' \item `prior_rate_*`: Columns containing success rate for each treatment arm, from all periods before the observations period of the simulation.
#' \item `*_assign_prob`: Columns containing probability of being assigned each treatment at the given period.
#' }
#' \item `bandits`: A `tibble` or `data.table` containing the UCB1 values or Thompson sampling posterior distributions for each period. Wide format,
#' each row is a period, and each columns is a treatment. Each row in this table represents the calculation from the given period
#' after its values were imputed, so row 2 represents the calculations made in period 3, but represent the impact of period 2's new assignments.
#' \item `assignment_probs`: A `tibble` or `data.table` containing the probability of being assigned each treatment arm at a given period. Wide format,
#' each row is a period, and each columns is a treatment. Each row represents the probability of being assigned each treatment at each period, these have not
#' been shifted like the bandits table.
#' \item `estimates`: A `tibble` or `data.table` containing the
#' AIPW (Augmented Inverse Probability Weighting) treatment effect estimates and variances, and traditional
#' sample means and variances, for each treatment arm. Long format, treatment arm, and estimate type are columns along with the mean
#' and variance.
#' \item `settings`: A named list of the configuration settings used in the trial.
#' }
#'
#' @details
#' For all the items laballed as a `data.frame` or `data.table`, `data.table`s will be used if the user passed `data` is a
#' `data.table`, `data.frame`s used otherwise.
#'
#' ## Clustering
#' Under adaptive probabilities of assignment,
#' traditional cluster assignment no longer makes sense, as then the updated probabilities have no impact.
#' Thus clustering is only performed at the period level, so across the experiment observations
#' in the same cluster may get different assignments.
#' In this case cluster level treatment effect estimates are not valid, so the user should ensure that clusters only persist across 1 period.
#'
#' ## Implementation
#'
#' At each period, either the Thompson sampling probabilities or UCB1 values are calculated based on
#' the outcomes from the number of `prior_periods` specified weighted by `discount_rate`. New treatments are then assigned randomly using the Thompson
#' sampling probabilities via the \href{https://cran.r-project.org/package=randomizr}{randomizr}
#' package, or as the treatment with the highest UCB1 values, while implementing the specific
#' treatment blocking and control augmentation specified.
#'
#' `control_augment` is a threshold probability for the control group, and the assignment probabilities
#' are changed to ensure that threshold is met. The other hybrid assignment is `random_assign_prop`. Here, the specified
#' proportion of the data is set aside to assign treatments randomly, while the rest of the data is assigned through the bandit procedure.
#'
#' After assigning treatments, observations with new treatments have their outcomes imputed
#' using success rates from the original randomized trial. These rates are estimated as grouped
#' means within each treatment arm. If blocking is specified, rates are estimated within each
#' combination of treatment arm and block. If clustering is specified, rates are not estimated
#' within each cluster, purely because if a cluster has changed assignment there are no observations from
#' the original trial in the cluster with that treatment given the cluster design.
#'
#' If `delayed_feedback = TRUE`, new dates of success will be imputed using the means
#' of those dates in the period, grouped by treatment block if necessary. Observations for which
#' their treatment changed, but their outcome was success in the original and simulation, do not have their date changed.
#' When the next period starts, the success dates are checked against the maximum/latest `assignment_date` for the period, and
#' if any success occurs after that, it is treated as a failure for the purpose of the bandit decision algorithms.
#'
#' ## Inference
#'
#' At the end of the simulation the results are aggregated together to calculate the Adaptively Weighted
#' Augmented Inverse Probability Estimator (Hadad et al. 2021) using the mean and variance formulas provided, under
#' the constant allocation rate adaptive schema. These estimators are unbiased and asymptotically normal under the adaptive
#' conditions and their differences are also un biased asymptotically normal estimators for treatment effects.
#' See \href{https://www.pnas.org/doi/pdf/10.1073/pnas.2014602118}{Hadad et al. (2021)}. Under clustering the formula is
#' slightly adjusted to consider the cluster means within each period as opposed to individual observations, which works better
#' when clusters are small. The variance is not adjusted for clustering.
#'
#' Inverse Probability Weighted (IPW) estimates are also provided using [estimatr::lm_robust()]. If blocking was specified
#' they are used as fixed effects. These estimates are unbiased but may have higher variance than the AIPW. HC2 or CR2 variances
#' are used (CR2 for clustering, HC2 otherwise). These cannot be used to estimate treatment effects, an F-statistic is provided,
#' which can be used to perform a joint test on the treatment arms using the randomization inference method from
#' \href{https://onlinelibrary.wiley.com/doi/abs/10.1111/ajps.12597}{Offer-Westort et al. (2021)}
#'
#'
#' ## Performance Concerns
#'
#' This procedure has the potential to be computationally expensive and time-consuming. Performance
#' depends on the relative size of each period, number of periods, and overall size of the dataset. This function has
#' separate support for `data.frame`s and `data.table`s. If a `data.frame` is passed, the function uses a combination of `dplyr`, `tidyr`
#' and base `R` to shape data, and run the simulation. However, if a `data.table` is passed the function exclusively uses the `data.table`
#' code for all the same operations.
#'
#' In general, smaller batches run faster under base `R`, while larger ones could benefit from the performance
#' and memory efficiencies provided by `data.table`. However, we've observed larger datasets can cause numerical
#' instability with some calculations in the Thompson sampling procedure. Internal safeguards exist to prevent this, but
#' the best way to preempt any issues is to set `prior_periods` to a low number.
#'
#' ## ` r > 1`
#' Multiple simulations allows researchers to gauge the variance
#' of the simulation procedure itself, by repeating it several times under different random states, using the same fixed data
#'
#' ### Parallel Processing
#'
#' The function provides support for parallel processing via the \href{https://cran.r-project.org/package=future}{future} and
#' \href{https://cran.r-project.org/package=furrr}{furrr} packages. When conducting a large
#' number of simulations, parallelization can improve performance if sufficient system resources are available.
#' Parallel processing must be explicitly set by the user, through `future::plan()`.
#' Windows users should set the plan to "multisession", while Linux and MacOS users can use "multicore" or "multisession".
#' Users running in a High Performance Computing environment (HPC), are encouraged to use
#' \href{https://cran.r-project.org/package=future.batchtools}{future.batchtools},
#' for their respective HPC scheduler.
#' Note that parallel processing is not guaranteed to work on all systems, and may require additional setup or debugging effort
#' from the user. For any issues, users are encouraged to consult the documentation of the above packages.
#'
#' For more information about how to use the function, please view the vignette.
#'
#' @references
#'
#' Agrawal, Shipra, and Navin Goyal. 2012.
#' "Analysis of Thompson Sampling for the Multi-Armed Bandit Problem."
#' \emph{Proceedings of the 25th Annual Conference on Learning Theory}, June 16, 39.1-39.26.
#' \url{https://proceedings.mlr.press/v23/agrawal12.html}.
#'
#' Asyuraa, F. C., S. Abdullah, and T. E. Sutanto. 2021. "Empirical Evaluation on Discounted Thompson Sampling for Multi-Armed Bandit Problem with Piecewise-Stationary Bernoulli Arms."
#'  Journal of Physics: Conference Series 1722 (1): 012096. \doi{10.1088/1742-6596/1722/1/012096}
#'
#' Auer, Peter, Nicolò Cesa-Bianchi, and Paul Fischer. 2002.
#' "Finite-Time Analysis of the Multiarmed Bandit Problem." \emph{Machine Learning}
#' 47 (2): 235–56. \doi{10.1023/A:1013689704352}.
#'
#' Bengtsson, Henrik. 2025. "Future: Unified Parallel and Distributed Processing in R for Everyone."
#' \url{https://cran.r-project.org/package=future}.
#'
#' Bengtsson, Henrik. 2025. "Future.Batchtools: A Future API for Parallel and Distributed Processing Using ‘Batchtools.’"
#' \url{https://cran.r-project.org/package=future.batchtools}.
#'
#' Garivier, Aurélien, and Eric Moulines. 2008. "On Upper-Confidence Bound Policies for Non-Stationary Bandit Problems."
#'  arXiv:0805.3415. Preprint, arXiv, May 22. \doi{10.48550/arXiv.0805.3415}
#'
#' Hadad, Vitor, David A. Hirshberg, Ruohan Zhan, Stefan Wager, and Susan Athey. 2021.
#' "Confidence Intervals for Policy Evaluation in Adaptive Experiments." \emph{Proceedings of the National Academy of Sciences of the United States of America} 118
#' (15): e2014602118. \doi{10.1073/pnas.2014602118}.
#'
#' Kuleshov, Volodymyr, and Doina Precup. 2014. "Algorithms for Multi-Armed Bandit Problems."
#' \emph{arXiv}. \doi{10.48550/arXiv.1402.6028}.
#'
#' Loecher, Thomas Lotze and Markus. 2022. "Bandit: Functions for Simple a/B Split Test and Multi-Armed Bandit Analysis."
#' \url{https://cran.r-project.org/package=bandit}.
#'
#' Offer‐Westort, Molly, Alexander Coppock, and Donald P. Green. 2021.
#' "Adaptive Experimental Design: Prospects and Applications in Political Science."
#' \emph{American Journal of Political Science} 65 (4): 826–44. \doi{10.1111/ajps.12597}..
#'
#' Slivkins, Aleksandrs. 2024. "Introduction to Multi-Armed Bandits." \emph{arXiv}. \doi{10.48550/arXiv.1904.07272}.
#'
#' Vaughan, Davis, Matt Dancho, and RStudio. 2022.
#' "Furrr: Apply Mapping Functions in Parallel Using Futures."
#' \url{https://cran.r-project.org/package=furrr}.
#'
#' @seealso \href{https://furrr.futureverse.org}{furrr}, \href{https://future.futureverse.org}{future}, [summary.mab()], [plot.mab()].
#'
#' @example inst/examples/single_mab_simulation_example.R
#' @export
mab_from_rct.bernoulli <- function(
  formula,
  data,
  algorithm,
  random_assign_prop = 0,
  control_augment = 0,
  control_condition = NULL,
  period_method,
  time_unit = NULL,
  period_length,
  prior_periods,
  discount_rate = 1,
  date_col = NULL,
  month_col = NULL,
  delayed_feedback = FALSE,
  assignment_date_col = NULL,
  success_date_col = NULL,
  whole_experiment = FALSE,
  ndraws = 5000,
  r = 1,
  seeds = NULL,
  verbose = FALSE,
  check_args = TRUE,
  keep_data = FALSE,
  ...
) {
  data_cols <- c(
    formula_parse(formula),
    date_col = date_col,
    month_col = month_col,
    assignment_date_col = assignment_date_col,
    success_date_col = success_date_col
  )
  blocking <- !base::is.null(data_cols$block_cols)
  clustering <- !base::is.null(data$cluster_col)

  prepped <- prep_rct_data(
    data = data,
    algorithm = algorithm,
    control_augment = control_augment,
    control_condition = control_condition,
    random_assign_prop = random_assign_prop,
    period_method = period_method,
    time_unit = time_unit,
    period_length = period_length,
    prior_periods = prior_periods,
    discount_rate = discount_rate,
    delayed_feedback = delayed_feedback,
    whole_experiment = whole_experiment,
    blocking = blocking,
    clustering = clustering,
    data_cols = data_cols,
    check_args = check_args,
    verbose = verbose,
    ndraws = ndraws,
    r = r,
    seeds = seeds,
    keep_data = keep_data
  )
  if (r == 1) {
    results <- simulate_mab(
      data = prepped$data,
      resimulation = TRUE,
      algorithm = prepped$char_args$algorithm,
      control_augment = control_augment,
      random_assign_prop = random_assign_prop,
      period_length = period_length,
      prior_periods = prior_periods,
      delayed_feedback = delayed_feedback,
      whole_experiment = whole_experiment,
      discount_rate = discount_rate,
      conditions = prepped$conditions,
      blocking = blocking,
      clustering = clustering,
      data_cols = prepped$data_cols,
      verbose = verbose,
      imputation_information = prepped$imputation_information,
      ndraws = ndraws,
      starts = prepped$period_starts,
      ends = prepped$period_ends
    )
    base::class(results) <- c("mab", base::class(results))
  } else {
    verbose_log(verbose, "Starting Simulations")
    mabs <- furrr::future_map(
      seeds,
      function(x) {
        set.seed(x)
        results <- simulate_mab(
          data = prepped$data,
          resimulation = TRUE,
          algorithm = prepped$char_args$algorithm,
          control_augment = control_augment,
          random_assign_prop = random_assign_prop,
          period_length = period_length,
          prior_periods = prior_periods,
          delayed_feedback = delayed_feedback,
          whole_experiment = whole_experiment,
          discount_rate = discount_rate,
          conditions = prepped$conditions,
          blocking = blocking,
          clustering = clustering,
          data_cols = prepped$data_cols,
          verbose = FALSE,
          imputation_information = prepped$imputation_information,
          ndraws = ndraws,
          starts = prepped$period_starts,
          ends = prepped$period_ends
        )
        results$assignment_quantities <- get_assignment_quantities(
          results,
          prepped$conditions
        )
        if (!keep_data) {
          results$final_data <- NULL
        }
        return(results)
      },
      .options = furrr::furrr_options(
        globals = list(
          simulate_mab = simulate_mab,
          data = prepped$data,
          resimulation = TRUE,
          data_cols = prepped$data_cols,
          imputation_information = prepped$imputation_information,
          time_unit = prepped$character_args$time_unit,
          period_length = period_length,
          prior_periods = prepped$character_args$prior_periods,
          algorithm = prepped$character_args$algorithm,
          whole_experiment = whole_experiment,
          perfect_assignment = prepped$character_args$perfect_assignment,
          conditions = prepped$conditions,
          blocking = blocking,
          assignment_method = assignment_method,
          control_augment = control_augment,
          keep_data = keep_data,
          ndraws = ndraws,
          random_assign_prop = random_assign_prop
        ),
        packages = c(
          "whatifbandit",
          "dplyr",
          "rlang",
          "tidyr",
          "bandit",
          "tibble",
          "lubridate",
          "purrr",
          "furrr",
          "randomizr",
          "data.table",
          "estimatr"
        ),
        seed = TRUE,
        ...
      ),
      .progress = verbose
    )
    verbose_log(verbose, "Collating Results")
    results <- condense_results(
      dt = ((data.table::is.data.table(data)) ||
        r * base::length(prepped$period_starts) > 100000),
      keep_data = keep_data,
      mabs = mabs,
      r = r
    )
    base::class(results) <- c("multiple.mab", base::class(results))
  }
  results$settings <- list(
    original_data = data,
    algorithm = prepped$char_args$algorithm,
    period_method = prepped$char_args$period_method,
    time_unit = prepped$char_args$time_unit,
    period_length = period_length,
    prior_periods = prior_periods,
    discount_rate = discount_rate,
    control_augment = control_augment,
    random_assign_prop = random_assign_prop,
    control = base::as.character(control_condition),
    conditions = prepped$conditions,
    delayed_feedback = delayed_feedback,
    whole_experiment = whole_experiment,
    blocking = blocking,
    block_cols = prepped$data_cols$block_cols$name,
    cluster_col = prepped$data_cols$cluster_col$name,
    ndraws = ndraws,
    delayed_feedback = delayed_feedback,
    keep_data = keep_data,
    r = r,
    seeds = seeds
  )
  base::class(results) <- c("fixed", class(results))
  return(results)
}
#------------------------------------------------------------------------------
#' Formula Parser
#' @description
#' Parsers the input formula for [mab_from_rct.bernoulli()]
#' @name formula_parse
#' @inheritParams mab_from_rct.bernoulli
#' @returns
#' @keywords internal

formula_parse <- function(formula) {
  formula <- as.character(formula)

  outcome <- formula[2]

  obc <- base::strsplit(formula[3], "\\+") |>
    base::lapply(base::trimws) |>
    base::unlist()

  conditions_col <- obc[1]
  other_vars <- base::lapply(
    base::list(
      obc[base::grepl("block\\((.*?)\\)", obc)],
      obc[base::grepl("cluster\\((.*?)\\)", obc)]
    ),
    gather_args
  )

  return(
    base::list(
      condition_col = conditions_col,
      success_col = outcome,
      block_cols = block(other_vars[[1]]$args),
      cluster_col = cluster(other_vars[[2]]$args)
    )
  )
}
#' Gather Args
#' @description Helper for formula parsing. Parses the expression, and splits the function call from the arguments.
#' @param x String representing an `R` expression, like `"block(x1)"`.
#' @returns A list containing the function call, and the arguments so `"Block(x1)"` gets turned into a list
#' with elements `block, "x1"`.

gather_args <- function(x) {
  if (base::length(x) == 0) {
    return(base::list(NULL))
  }
  call <- rlang::parse_expr(x) |>
    base::as.list()

  args <- base::vapply(
    call[-1],
    rlang::as_label,
    base::character(1)
  )
  return(list(call = call[[1]], args = args))
}

# Helpers not requiring documentation, simply identity functions for block and cluster cases.

block <- function(...) {
  base::c(...)
}
cluster <- function(x) {
  x
}

#' Verbose Printer
#' @description Shorthand Function for checking `verbose` and then printing if TRUE
#' @name verbose_log
#' @param message The message to be printed to screen, as a string.
#' @param log Logical; Whether or not to print the message, this will always be
#' the `verbose` argument passed from higher functions.
#' @returns Text output of `message` to the console when `log = TRUE`. If
#' `log = FALSE`, returns nothing.
#' @keywords internal

verbose_log <- function(log, message) {
  if (log) {
    base::cat(message, "\n")
  }
}


#' @name get_assignment_quantitites
#' @title Calculates Number of Observations Assigned to Each Treatment
#' @description Takes the output from [simulate_mab_rct.bernoulli()], and
#' calculates the number of observations assigned to each treatment group in the adaptive trial.
#' @param simulation Output from [simulate_mab_rct.bernoulli()]
#' @param conditions Character vector containing the names of all the treatment conditions in the trial.
#' @returns Named numeric vector containing number of observations assigned to each treatment group
#' @keywords internal
get_assignment_quantities <- function(simulation, conditions) {
  UseMethod("get_assignment_quantities", simulation$final_data)
}
#' @method get_assignment_quantities data.frame
#' @description get_assignment_quantities for `data.frame`s
#' @inheritParams get_assignment_quantities
#' @noRd
get_assignment_quantities.data.frame <- function(simulation, conditions) {
  count_summary <- simulation$final_data |>
    dplyr::group_by(mab_condition) |>
    dplyr::count()

  count_vec <- rlang::set_names(count_summary$n, count_summary$mab_condition)

  if (length(count_vec) < length(conditions)) {
    missing_conds <- base::setdiff(
      conditions,
      base::names(count_vec)
    )
    count_vec[missing_conds] <- 0
  }
  return(count_vec)
}
#-------------------------------------------------------------------
#' @method get_assignment_quantities data.table
#' @description get_assignment_quantities for `data.table`s
#' @inheritParams get_assignment_quantities
#' @noRd
get_assignment_quantities.data.table <- function(simulation, conditions) {
  count_summary <- simulation$final_data[, .N, by = mab_condition]
  data.table::setorder(count_summary, mab_condition)
  count_vec <- rlang::set_names(count_summary$N, count_summary$mab_condition)
  if (length(count_vec) < length(conditions)) {
    missing_conds <- base::setdiff(
      conditions,
      base::names(count_vec)
    )
    count_vec[missing_conds] <- 0
  }
  return(count_vec)
}
#-----------------------------------------------------------------

#' @name condense_results
#' @title Condenses results of repeated simulations.
#' @inheritParams mab_from_rct.bernoulli
#' @param dt Logical; Whether to output `data.table`s or `tibble`s. When` r * number_of_periods > 100000`, `dt = TRUE`, even if the user passed data is not a
#' `data.table`.
#' @param mabs List of outputs from repeated [simulate_mab_rct.bernoulli()] calls.
#' @returns A named list containing
#' \itemize{
#' \item `final_data_nest:` `tibble` or `data.table` containing the nested `tibble`s/`data.table`s from each trial. Only provided when `keep_data = TRUE`.
#' \item `bandits`: A `tibble` or `data.table` containing the UCB1 values or Thompson Sampling posterior distributions for each period and trial. Wide format,
#' each row is a period, and each columns is a treatment.
#' \item `assignment_probs`: A `tibble` or `data.table` containing the probability of being assigned each treatment arm at a given period and trial. Wide format,
#' each row is a period, and each columns is a treatment.
#' \item `estimates`: A `tibble` or `data.table` containing the all estimates and variances for each arm.
#' Long format, treatment arm, and estimate type are columns along with the mean estimates
#' and variance estimates.
#' }
#' @details
#' This function iterates over every element in `mabs` and extracts the required element to place in a condensed list
#' for the final output.
#'
#' @keywords internal

condense_results <- function(dt, keep_data, mabs, r) {
  items <- c(
    "bandits",
    "assignment_probs",
    "estimates",
    "assignment_quantities"
  )

  if (dt) {
    results <- lapply(items, \(item) {
      all <- lapply(seq_len(r), function(i) {
        if (item == "assignment_quantities") {
          as.list(mabs[[i]][[item]])
        } else {
          mabs[[i]][[item]]
        }
      })
      result <- data.table::rbindlist(all, idcol = "trial", use.names = TRUE)
      result[, trial := as.numeric(trial)]
      return(result)
    })
    names(results) <- items
    if (keep_data) {
      results$final_data_nest <- data.table::data.table(
        trial = base::seq_len(r),
        data = purrr::map(mabs, ~ .x$final_data)
      )
    } else {
      results$final_data_nest <- NULL
    }
  } else {
    results <- purrr::map(items, function(item) {
      result <- purrr::map(seq_len(r), function(i) mabs[[i]][[item]]) |>
        dplyr::bind_rows(.id = "trial") |>
        dplyr::mutate(trial = as.numeric(trial))
      return(result)
    })
    names(results) <- items

    if (keep_data) {
      results$final_data_nest <- tibble::tibble(
        trial = base::seq_len(r),
        data = purrr::map(mabs, ~ .x$final_data)
      )
    } else {
      results$final_data_nest <- NULL
    }
  }

  dims <- base::dim(mabs[[1]]$ipw_vcov)
  results$ipw_vcov <- base::lapply(mabs, \(x) {
    x$ipw_vocv
  }) |>
    base::unlist() |>
    base::arrary(dim = c(dims, base::length(mabs)))

  return(results)
}
